### ISSUE TITLE
1%: Breakdown of .01% giving

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/design#54]
It's unclear right now what this is supposed to show.

**Comment by cweber** [comment]
![img_4639](https://cloud.githubusercontent.com/assets/417657/7147818/cc18b292-e2cb-11e4-9c99-e7ee3a1c6dea.JPG)

**Comment by cweber** [comment]
![img_4642](https://cloud.githubusercontent.com/assets/417657/7147840/e55f4a90-e2cb-11e4-847e-d8b0c5dec0fc.JPG)

**Comment by cweber** [comment]
[Waiting on CRP]

Show impact of 1% giving within each category.

Ideally, also show partisanship within each 1% contribution (to each category).

USED TO BE THIS!
![screen shot 2015-04-14 at 5 44 33 pm](https://cloud.githubusercontent.com/assets/417657/7148338/19bc34b6-e2d0-11e4-920e-64a9ad614dc1.png)

Maybe will be this?
![img_4643](https://cloud.githubusercontent.com/assets/417657/7148377/5a414ef4-e2d0-11e4-897c-9325ba908cfa.jpg)

**Comment by cweber** [comment]
Peter says this is the final decision!

PIE ONLY 
1% ONLY

https://docs.google.com/a/sunlightfoundation.com/spreadsheets/d/1bLyFrkkcGMHyFTnIiGaW41cqlQUgWSLaRC9cRX8YFbQ/edit#gid=1676683126

Breakdown Tab.

**Comment by heyitsolivia** [comment]
![breakdown-of-giving](https://cloud.githubusercontent.com/assets/1198350/7309085/91f542a0-e9e8-11e4-9611-77d1cba63ffb.png)

**Comment by heyitsolivia** [comment]
Descriptions should say PACs and Super PACs

**Comment by cweber** [comment]
![breakdown-of-giving](https://cloud.githubusercontent.com/assets/417657/7325337/ba653a1c-ea8b-11e4-9b1d-41377d9628f1.png)
