### ISSUE TITLE
1%: Silly .01% of 100 pie chart

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/design#56]

**Comment by cweber** [comment]
![screen shot 2015-04-14 at 5 31 44 pm](https://cloud.githubusercontent.com/assets/417657/7147883/3ac6dfe8-e2cc-11e4-9626-276f2cd38d8b.png)

**Comment by heyitsolivia** [comment]
![who-recieved-money](https://cloud.githubusercontent.com/assets/1198350/7307920/0deb6624-e9de-11e4-9b25-3c0219a46c3d.png)

Needs CRP logo, and a source

**Comment by heyitsolivia** [comment]
![who-recieved-money](https://cloud.githubusercontent.com/assets/1198350/7309074/881bbd54-e9e8-11e4-934d-03d073f28b72.png)
