### ISSUE TITLE
How the design team is trying to design in the open.

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/design#71]
What we've considered around open source design and designing in the open. How we're experimenting with that process.

**Comment by heyitsolivia** [comment]
I have feelings about this topic! but I think this post can and should have input from all of us.

**Comment by cweber** [comment]
Agreed. I think writing this post will probably help us  solidify a 'position' on it, so should be a collaborative piece. 

*really wish single tasks could be assigned to multiple people.

**Comment by heyitsolivia** [comment]
Just finished this blog post
