### ISSUE TITLE
Party Preferences of the .01%

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/design#74]
Title: Party Preferences of the .01%
Subhed: The biggest donors tilt toward conservatives

**Comment by cweber** [comment]
The trouble with pie charts is... I actually think pie charts can be fine, but comparing two pie charts is a bit nuts. In this case, without the numbers/key, those pie charts would basically look the same. Probably necessary to do this as a bar chart, but it was kind of a good experiment to prove that this doesn't really work.

![party-preferences](https://cloud.githubusercontent.com/assets/417657/7501427/c64fef1e-f401-11e4-924c-fcffa5f6ea4c.png)

**Comment by heyitsolivia** [comment]
Pretty good proof that pie charts shouldn't be used as a tool for comparison.

go bar charts

**Comment by cweber** [comment]
Probably a cool example to keep around to be like, "See? Sometimes we think about it too, but ...Um no."

**Comment by cweber** [comment]
And now...as a grouped bar chart!

![party-preferences](https://cloud.githubusercontent.com/assets/417657/7501880/a406be8e-f405-11e4-84ff-cffbb32489c8.png)

**Comment by cweber** [comment]
But wide...to balance the other bar chart we just made.

![party-preferences](https://cloud.githubusercontent.com/assets/417657/7501926/f96671d0-f405-11e4-867e-288d84277b78.png)

**Comment by heyitsolivia** [comment]
do you think it'd be helpful to keep the 25% and and 75% grid lines in there for a better sense of the numbers?

I also think the vertical axis labels should be consistent: 100% and 50%

**Comment by cweber** [comment]
Yeah. I thought about keeping 25% and 75%. I'll add that.

re: axis labels. I don't know... for some reason it's always been my pattern to only label the unit on the top. So if it was on a scale of $1,000 I would only prepend the number with the dollar sign for the max unit.

Seems like this should be a thing that Tufte has an opinion about.

**Comment by heyitsolivia** [comment]
If we go by our styleguide, it seems like axis values are labeled with units when available: http://design.sunlightlabs.com/projects/Sunlight-StyleGuide-DataViz.pdf

**Comment by cweber** [comment]
Yep. Ok. I'll default to that for now to get it out. Seems redundant.

**Comment by cweber** [comment]
New y axis label and % on everything!

![party-preferences](https://cloud.githubusercontent.com/assets/417657/7502866/1c98fb58-f40d-11e4-9283-2442140d79cb.png)

**Comment by heyitsolivia** [comment]
:+1:

leaving the twitter discussion about labeling axis values here for future reference: https://twitter.com/caitlinweber/status/596043041929973760
