### ISSUE TITLE
Tables for Tim

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/design#78]
Create styles for a group of embeddable tables for @timball's blog post.

**Comment by heyitsolivia** [comment]
Brought Tim's html tables closer inline with Sunlight's dataviz header styles— helps to brand the content as Sunlight Foundation and to provide context.

![screen shot 2015-05-20 at 6 20 38 pm](https://cloud.githubusercontent.com/assets/1198350/7737897/f9d33942-ff1c-11e4-8ef6-a6b3dd221cbe.png)

Grading rubric for blog post
![grade-explanation](https://cloud.githubusercontent.com/assets/1198350/7737858/ada11e22-ff1c-11e4-830a-308eaad0e206.jpg)

**Comment by heyitsolivia** [comment]
Additional thoughts: These styles and icons could and should be extracted for reuse somewhere down the line, in the likely event we need to do something like this again.

**Comment by cweber** [comment]
Can you make a new issue in @sunlightlabs/design for extracting for reusability? Maybe one for table/iframe styles and one for icons?
